title: Maciek's Blog
description: Thoughts on software, vibe coding, and building things.
baseurl: "/blog"
url: "https://szulcmaciej.github.io"
theme: minima

author: Maciek Szulc

github_username: szulcmaciej
linkedin_username: szulcmaciej1
twitter_username: surfy_nerd

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/szulcmaciej" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/szulcmaciej1/" }
    - { platform: x, user_url: "https://x.com/surfy_nerd" }

plugins:
  - jekyll-feed
